### ISSUE TITLE
Looking for contributors before release

### ISSUE THREAD

**Issue by sidwebworks** [sidwebworks/zors#1]
Everything in terms of core functionality is done, all that is left is
- Add more tests
- JS Doc comments for better IDE experience
- README.md documentation

I am looking for contributors on these things, would really appreciate if someone wants to help

Regardless, I will continue to finish these tasks on my own as well.

**Comment by saurabhan** [comment]
Willing to help

**Comment by jaynarayan-vaishnav** [comment]
I am in for the documentation part

**Comment by sidwebworks** [comment]
Hey, thanks for reaching out I have started writing unit and integration tests for the package and will keep adding more in the mean time,

You guys can have a look at them, get familiar with some of the package exports ("zors", "defineCommand", ..etc)

That should help you with documentation work, in the start will we just have JS DOC comments and README.md as our main documentation sources. As this gets a bit more mature we will add a documentation site generated from our Markdown files only.

there are some other contributors as well who are currently getting familiar with the project.

If there is anything that I missed out, feel free to ask here or DM me on discord (Sid_web_works#5267)

@saurabhan @jaynarayan-vaishnav

**Comment by sidwebworks** [comment]
Just for context, this is kinda how the README.md file will be structured https://github.com/tj/commander.js#readme

**Comment by jaynarayan-vaishnav** [comment]
Sorry @sidwebworks  was not active due to health issue but will do some simple contributions to this projects as i understand some things about this project and also i am a beginner 🙂
